stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  # On définit le tag pour éviter les répétitions
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build_image:
  stage: build
  tags:
    - debian
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # On build avec le SHA unique pour la traçabilité et le latest pour la praticité
    - docker build -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest .
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_k3s:
  stage: deploy
  tags:
    - debian
  before_script:
    # Installation des outils nécessaires
    - which ssh || (apt-get update && apt-get install -y openssh-client)
    - which envsubst || (apt-get update && apt-get install -y gettext)
    - chmod 600 $CI_CD_SSH_KEY
  script:
    # 1. Préparation du manifeste
    # envsubst va remplacer ${CI_COMMIT_SHA} et ${CI_REGISTRY_IMAGE} dans ton deployment.yaml
    - envsubst < k8s/deployment.yaml > k8s/deployment_ready.yaml
    
    # 2. Transfert vers le VPS (Kamal @ DevopsNotes)
    - scp -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY k8s/deployment_ready.yaml kamal@$SERVER_IP:/home/kamal/infrastructure/apps/portfolio-portal/k8s/deployment.yaml
    - scp -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY k8s/portfolio-ingress.yaml kamal@$SERVER_IP:/home/kamal/infrastructure/apps/portfolio-portal/k8s/portfolio-ingress.yaml
    
    # 3. Application de la configuration sur le cluster K3s
    # Note : Le apply -f sur le dossier permet de mettre à jour Ingress et Deployment d'un coup
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY kamal@$SERVER_IP "sudo k3s kubectl apply -f /home/kamal/infrastructure/apps/portfolio-portal/k8s/"
    
    # 4. Vérification du déploiement (Optionnel mais recommandé)
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY kamal@$SERVER_IP "sudo k3s kubectl rollout status deployment portfolio-portal-deployment -n portfolio-prod"