stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Build de l'image Docker
build_image:
  stage: build
  tags:
    - deploy_production
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

# DÃ©ploiement sur K3s
deploy_k3s:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-network --no-cache openssh-client gettext
    - chmod 600 $CI_CD_SSH_KEY
  script:
    - envsubst < k8s/deployment.yaml > k8s/deployment_ready.yaml
    - scp -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY k8s/deployment_ready.yaml root@$SERVER_IP:/root/portfolio-portal/deployment.yaml
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY root@$SERVER_IP "k3s kubectl apply -f /root/portfolio-portal/deployment.yaml"
  only:
    - main