stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build_image:
  stage: build
  tags:
    - deploy_production
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy_k3s:
  stage: deploy
  tags:
    - deploy_production
  before_script:
    # Installation propre des outils si absents
    - which ssh || (apt-get update && apt-get install -y openssh-client)
    - envsubst -V || (apt-get update && apt-get install -y gettext)
    - chmod 600 $CI_CD_SSH_KEY
  script:
    # 1. Préparation du manifeste (injection du tag d'image $CI_COMMIT_SHA)
    - envsubst < k8s/deployment.yaml > k8s/deployment_ready.yaml
    
    # 2. Transfert sécurisé vers le VPS
    - scp -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY k8s/deployment_ready.yaml kamal@$SERVER_IP:/home/kamal/infrastructure/apps/portfolio-portal/k8s/deployment.yaml
    
    # 3. L'ÉTAPE MANQUANTE : Appliquer les changements sur le cluster
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY kamal@$SERVER_IP "sudo k3s kubectl apply -f /home/kamal/infrastructure/apps/portfolio-portal/k8s/deployment.yaml"
    
    # 4. (Optionnel) Redémarrer proprement pour être sûr que la nouvelle image est tirée
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY kamal@$SERVER_IP "sudo k3s kubectl rollout restart deployment portfolio-portal-deployment -n portfolio-prod"
  only:
    - main