stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Build de l'image Docker
build_image:
  stage: build
  tags:
    - deploy_production
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

# Déploiement sur K3s
deploy_k3s:
  stage: deploy
  tags:
    - deploy_production
  before_script:
    - medical_term() { which $1 || (sudo apt-get update && sudo apt-get install -y $2); }
    - which ssh || (sudo apt-get update && sudo apt-get install -y openssh-client)
    - which envsubst || (sudo apt-get update && sudo apt-get install -y gettext)
    - chmod 600 $CI_CD_SSH_KEY
  script:
    # 1. Préparation du manifeste avec les variables d'environnement
    - envsubst < k8s/deployment.yaml > k8s/deployment_ready.yaml
    
    # 2. Transfert vers le nouveau chemin dans le dossier infrastructure
    - scp -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY k8s/deployment_ready.yaml kamal@$SERVER_IP:/home/kamal/infrastructure/apps/portfolio-portal/k8s/deployment.yaml
    
    # 3. Application du manifeste depuis le nouvel emplacement
    - ssh -o StrictHostKeyChecking=no -i $CI_CD_SSH_KEY kamal@$SERVER_IP "sudo k3s kubectl apply -f /home/kamal/infrastructure/apps/portfolio-portal/k8s/deployment.yaml"
  only:
    - main