apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-portal-deployment
  namespace: portfolio-prod
  labels:
    app: portfolio-portal
    owner: kamal
    project: devopsnotes
spec:
  replicas: 1
  # Stratégie de mise à jour : garantit zéro coupure (Zero Downtime)
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: portfolio-portal
  template:
    metadata:
      labels:
        app: portfolio-portal
    spec:
      # Sécurité : On utilise un secret pour tirer l'image du registre GitLab
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: portfolio-portal
        # Injection dynamique via envsubst dans ta CI/CD
        image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
        imagePullPolicy: Always
        
        ports:
        - containerPort: 3000
          name: http-port

        volumeMounts:
        - name: next-cache
          mountPath: /app/.next/cache

        # Variables d'environnement pour Next.js (si besoin)
        env:
          - name: NODE_ENV
            value: "production"

        # Gestion des ressources (FinOps & Stabilité)
        # On limite pour éviter qu'un bug ne sature ton VPS Ubuntu
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"

        # Health Checks : K3s redémarre le conteneur s'il plante
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10

      # Sécurité supplémentaire : évite l'exécution en root si possible
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      volumes:
      - name: next-cache
        emptyDir: {}