apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-portal-ingress
  namespace: portfolio-prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true" # Force la redirection vers HTTPS
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portfolio.devopsnotes.org
    secretName: portfolio-portal-tls # Le nom du secret qui contiendra le certificat
  rules:
  - host: portfolio.devopsnotes.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-portal-service
            port:
              number: 80