apiVersion: v1
kind: Namespace
metadata:
  name: portfolio-prod
---
apiVersion: apps/v1
kind: Deployment     
metadata:
  name: portfolio-portal-deployment
  namespace: portfolio-prod
  labels:
    app: portfolio-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-portal   
  template:
    metadata:
      labels:
        app: portfolio-portal
    spec:
      containers:
      - name: portfolio-portal
        image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-portal-service
  namespace: portfolio-prod
spec:
  selector:
    app: portfolio-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-portal-ingress
  namespace: portfolio-prod
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: portfolio.devopsnotes.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portfolio-portal-service
            port:
              number: 80