apiVersion: v1
kind: Service
metadata:
  name: portfolio-portal-service
  namespace: portfolio-prod
spec:
  selector:
    app: portfolio-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
